---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      # K8s and operator SDK, we need to handle these manually
      - dependency-name: github.com/operator-framework/*
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/*
  - package-ecosystem: gomod
    target-branch: "release-2.5"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      # K8s and operator SDK, we need to handle these manually
      - dependency-name: github.com/operator-framework/*
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/*
      # 2.5 tracks Submariner 0.12
      - dependency-name: github.com/submariner-io/*
        ignore: ">= 0.13.0"
  - package-ecosystem: gomod
    target-branch: "release-2.6"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      # K8s and operator SDK, we need to handle these manually
      - dependency-name: github.com/operator-framework/*
      - dependency-name: k8s.io/*
      - dependency-name: sigs.k8s.io/*
      # 2.6 tracks Submariner 0.13
      - dependency-name: github.com/submariner-io/*
        ignore: ">= 0.14.0"
