apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gateways.submariner.io
  ownerReferences:
  - apiVersion: apiextensions.k8s.io/v1beta1
    controller: true
    blockOwnerDeletion: true
    kind: CustomResourceDefinition
    name: submarinerconfigs.submarineraddon.open-cluster-management.io
    uid: {{ .ConfigCRDUID }}
spec:
  group: submariner.io
  names:
    kind: Gateway
    listKind: GatewayList
    plural: gateways
    singular: gateway
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: High availability status of the Gateway
      jsonPath: .status.haStatus
      name: HA Status
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          status:
            properties:
              connections:
                items:
                  properties:
                    endpoint:
                      properties:
                        backend:
                          type: string
                        backend_config:
                          additionalProperties:
                            type: string
                          type: object
                        cable_name:
                          type: string
                        cluster_id:
                          type: string
                        healthCheckIP:
                          type: string
                        hostname:
                          type: string
                        nat_enabled:
                          type: boolean
                        private_ip:
                          type: string
                        public_ip:
                          type: string
                        subnets:
                          items:
                            type: string
                          type: array
                      required:
                      - backend
                      - cable_name
                      - cluster_id
                      - hostname
                      - nat_enabled
                      - private_ip
                      - public_ip
                      - subnets
                      type: object
                    latency:
                      description: LatencySpec describes the round trip time information
                        in nanoseconds for a packet between the gateway pods of two
                        clusters.
                      properties:
                        averageRTT:
                          format: int64
                          type: integer
                        lastRTT:
                          description: TODO This shall be deleted once the operator
                            is using the latest. Using Optional to avoid validation
                            errors when this field is not used.
                          format: int64
                          type: integer
                        maxRTT:
                          format: int64
                          type: integer
                        minRTT:
                          format: int64
                          type: integer
                        stddevRTT:
                          format: int64
                          type: integer
                      type: object
                    latencyRTT:
                      description: LatencySpec describes the round trip time information
                        for a packet between the gateway pods of two clusters.
                      properties:
                        average:
                          type: string
                        last:
                          type: string
                        max:
                          type: string
                        min:
                          type: string
                        stdDev:
                          type: string
                      type: object
                    status:
                      type: string
                    statusMessage:
                      type: string
                  required:
                  - endpoint
                  - status
                  - statusMessage
                  type: object
                type: array
              haStatus:
                type: string
              localEndpoint:
                properties:
                  backend:
                    type: string
                  backend_config:
                    additionalProperties:
                      type: string
                    type: object
                  cable_name:
                    type: string
                  cluster_id:
                    type: string
                  healthCheckIP:
                    type: string
                  hostname:
                    type: string
                  nat_enabled:
                    type: boolean
                  private_ip:
                    type: string
                  public_ip:
                    type: string
                  subnets:
                    items:
                      type: string
                    type: array
                required:
                - backend
                - cable_name
                - cluster_id
                - hostname
                - nat_enabled
                - private_ip
                - public_ip
                - subnets
                type: object
              statusFailure:
                type: string
              version:
                type: string
            required:
            - connections
            - haStatus
            - localEndpoint
            - statusFailure
            - version
            type: object
        required:
        - status
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
