apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .ManagedClusterName }}
  namespace: {{ .SubmarinerBrokerNamespace }}
  labels:
    cluster.open-cluster-management.io/submariner-cluster-sa: {{ .ManagedClusterName }}
